mirte_telemetrix_cpp_bno055:
  bno055_module_names: 
      type: string_array
      default_value: []
      description: "List of module names to be loaded"
  modules:
    
    __map_bno055_module_names:
        type:
          type: string
          default_value: NONE
          description: "Type of power sensor (bno055)"
        pins:
          sda:
            type: string
            default_value: "-1"
            description: "Pin number for I2C SDA line"
          scl:
            type: string
            default_value: "-1"
            description: "Pin number for I2C SCL line"
        addr:
          type: int
          default_value: 0x28
          description: "I2C address of the bno055 sensor, TODO: currently unused"
        frame_id:
          type: string
          default_value: "imu_link"
        connector:
          type: string
          default_value: NONE
          description: "Connector to which the bno055 sensor is connected"