mirte_telemetrix_cpp_mpu9250:
  mpu9250_module_names: 
      type: string_array
      default_value: []
      description: "List of module names to be loaded"
  modules:
    
    __map_mpu9250_module_names:
        type:
          type: string
          default_value: NONE
          description: "Type of power sensor (mpu9250)"
        pins:
          sda:
            type: string
            default_value: "-1"
            description: "Pin number for I2C SDA line"
          scl:
            type: string
            default_value: "-1"
            description: "Pin number for I2C SCL line"
        addr:
          type: int
          default_value: 0x68
          description: "I2C address of the mpu9250 sensor"
        frame_id:
          type: string
          default_value: "imu_link"
        connector:
          type: string
          default_value: NONE
          description: "Connector to which the mpu9250 sensor is connected"