/**:
  ros__parameters:
    port: /dev/ttyACM0
    device:
      mirte:
        type: breadboard
        board: raw
    #    max_frequency: 50
    distance:
      left:
        name: left
        device: mirte
        pins:
          trigger: D9
          echo: D8
      # right:
      #   name: right
      #   device: mirte
      #   pins:
      #     trigger: A5
      #     echo: A6
    # encoder:
    #   left:
    #     name: left
    #     device: mirte
    #     pins:
    #       pin: D27           # pin needs interrupt support
    #     ticks_per_wheel: 20
    # #   # right:
    # #   #   name: right
    # #   #   device: mirte
    # #   #   pins:
    # #   #     pin: D3            # pin needs interrupt support
    # #   #   ticks_per_wheel: 20
    # intensity:
    #   left:
    #     name: left 
    #     device: mirte
    #     max_frequency: 10
    #     differential: 0
    #     pins:
    #       digital: D15
    #       analog: A3         # pin needs analog input
    # #   right:
    # #     name: right
    # #     device: mirte
    # #     pins:
    # #       digital: D8
    # #       analog: A1         # pin needs analog input
    # # oled:
    # #     oled:
    # #       device: mirte
    # #       connector: I2C1 # depending on arduino
    # servo:
    #   left:
    #     name: left
    #     device: mirte
    #     pins:
    #       pin: D23               # pin needs PWM
    # #   right:
    # #     name: right
    # #     device: mirte
    # #     pins:
    # #       pin: D10               # pin needs PWM
    # keypad:
    #   yellow:
    #     name: yellow
    #     device: mirte
    #     pins:
    #       pin: A6              # pin needs analog input
    # motor:
    #   left:
    #     name: left
    #     device: mirte
    #     type: ddp
    #     pins:
    #       d1: D22
    #       d2: D23
    #       p1: D25
    #   right:
    #     name: right
    #     device: mirte
    #     type: ddp
    #     pins:
    #       d1: D25
    #       d2: D26
    #       p1: D27
