/**:
  ros__parameters:
    device:
      mirte:
        type: pcb
        version: 0.6
        max_frequency: 50
    modules:
      motorservocontroller:
        device: mirte
        type: PCA9685
        addr: 0x41
        connector: I2C1
        frequency: 100
        motors: # TODO: No Idea which motor configuration is correct.
          rear_left:
            pin_A: 6 #0
            pin_B: 7 #1
          front_left:
            pin_A: 2
            pin_B: 3
          rear_right:
            pin_A: 5
            pin_B: 4
          front_right:
            pin_A: 1
            pin_B: 0
      servo_controller:
        device: mirte
        type: Hiwonder_Servo
        pins:
          rx: 0
          tx: 1
        servos:
          shoulder_pan:
            id: 2
            home_out: 12000
            min_angle_out: 3400
            max_angle_out: 21000
            invert: false
          shoulder_lift:
            id: 3
            home_out: 11450
            min_angle_out: 2832
            max_angle_out: 20000
            invert: false
          elbow:
            id: 4
            home_out: 11750
            min_angle_out: 120
            max_angle_out: 21000
            invert: false
          wrist:
            id: 5
            home_out: 12200
            min_angle_out: 1128
            max_angle_out: 21000
            invert: false
          gripper:
            id: 6
            home_out: 10524
            min_angle_out: 6168
            max_angle_out: 14224
            invert: false
#          servoH1:
#            id: 3
#            min_angle: 9000
#            max_angle: 14000
#          servoH2:
#            id: 4
#            min_angle: 800
#            max_angle: 4000
      power_watcher:
        device: mirte
        type: INA226
        connector: I2C1
        addr: 0x40
        min_voltage: 11.1
        max_current: 5
        max_voltage: 15
        turn_off_time: 10
        power_low_time: 20
        percentage_led_pin: GPIO4_B4 # 12 = B4, left-most led on usb switcher pcb
    encoder:
      left_front:
        name: left_front
        device: mirte
        pins:
          A: 15 #21
          B: 14 #20
      left_rear:
        name: left_rear
        device: mirte
        pins:
          A: 17
          B: 16
      right_front:
        name: right_front
        device: mirte
        pins:
          A: 19
          B: 18
      right_rear:
        name: right_rear
        device: mirte
        pins:
          A: 20
          B: 21
    oled:
      oled:
        device: mirte
        connector: I2C1
