/**:
  ros__parameters:
    device:
      mirte:
        type: pcb
        version: 0.6
        max_frequency: 50
    modules:
      motorservocontroller:
        device: mirte
        type: PCA9685
        addr: 0x41
        connector: I2C1
        frequency: 100
        motors: # TODO: No Idea which motor configuration is correct.
          left_rear:
            pin_A: 6 #0
            pin_B: 7 #1
          left_front:
            pin_A: 2
            pin_B: 3
          right_rear:
            pin_A: 5
            pin_B: 4
          right_front:
            pin_A: 1
            pin_B: 0
          # left_front:
          #   pin_A: 8
          #   pin_B: 9
          # left_rear:
          #   pin_A: 10
          #   pin_B: 11
          # right_front:
          #   pin_A: 12
          #   pin_B: 13
          # right_rear:
          #   pin_A: 14
          #   pin_B: 15
        # servos:
        #   servo1:
        #     pin: 1
      servo_controller:
        device: mirte
        type: Hiwonder_Servo
        pins:
          rx: 0
          tx: 1
        servos:
          servoH1:
            id: 3
            min_angle: 9000
            max_angle: 14000
          servoH2:
            id: 4
            min_angle: 800
            max_angle: 4000
      power_watcher:
        device: mirte
        type: INA226
        connector: I2C1
        addr: 0x40
        min_voltage: 11.1
        max_current: 5
        max_voltage: 15
        turn_off_time: 10
        power_low_time: 20
        percentage_led_pin: GPIO4_B4 # 12 = B4, left-most led on usb switcher pcb
    encoder:
      left_front:
        name: left_front
        device: mirte
        pins:
          A: 15 #21
          B: 14 #20
      left_rear:
        name: left_rear
        device: mirte
        pins:
          A: 17
          B: 16
      right_front:
        name: right_front
        device: mirte
        pins:
          A: 19
          B: 18
      right_rear:
        name: right_rear
        device: mirte
        pins:
          A: 20
          B: 21
