/**:
  ros__parameters:
    device:
      mirte:
        type: breadboard
        board: raw             # current setup is an example for the arduino nano
        version: 0.8
        max_frequency: 50
    # distance:
    #   # left:
    #   #   name: left
    #   #   device: mirte
    #   #   connector: SRF1
    #   # right:
    #   #   name: right
    #   #   device: mirte
    #   #   connector: SRF2
    #   right2:
    #     name: right2
    #     device: mirte
    #     pins:
    #       trigger: 1
    #       echo: 2
    #   right3:
    #     name: right3
    #     device: mirte
    #     pins:
    #       trigger: 11
    #       echo: 21
    #   right4:
    #     name: right4
    #     device: mirte
    #     pins:
    #       trigger: 12
    #       echo: 22
    
    # encoder:
    #   left:
    #     name: left
    #     device: mirte
    #     pins:
    #       pin: 2             # pin needs interrupt support
    #     ticks_per_wheel: 20
    #   right:
    #     name: right
    #     device: mirte
    #     pins:
    #       pin: 3             # pin needs interrupt support
    #     ticks_per_wheel: 20
    #   right2:
    #     name: right2
    #     device: mirte
    #     pins:
    #       A: 5             # pin needs interrupt support
    #       B: 4
    #     ticks_per_wheel: 20