---
# CHECK: is this even used?
ticks: 1320  # TODO: check 11pps*30reduction *4
separate_update_format: "/io/motor/set_%s_speed" # use %s for motor name
single_update_name: "/io/set_multiple_motor_speeds"
use_topic_update: true
use_single_update: true
cmd_vel_deadzone: 10
cmd_vel_update_deadzone: 3
encoder_topic_format: "/io/encoder/%s" # use %s for encoder name